### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jadonogh** [mghcdac/ecg_respiration_sleep_staging#2]
@Hockey86 do you plan on making this code publicly available? If so, I'd recommend placing a license in the folder with the code (MIT license is most common).

https://opensource.org/licenses/MIT

**Comment by Hockey86** [comment]
> @Hockey86 do you plan on making this code publicly available? If so, I'd recommend placing a license in the folder with the code (MIT license is most common).
> 
> https://opensource.org/licenses/MIT

Thanks Jake! Yes, it should be publicly available. Added MIT license.
