### ISSUE TITLE
"Excuse me, how is the npz file loaded at line 123 in the dataset.py file obtained? I didn't see any code in other files that generates the npz file."

### ISSUE THREAD

**Issue by lili084** [mghcdac/ecg_respiration_sleep_staging#3]
![image](https://github.com/bdsp-core/ecg_respiration_sleep_staging/assets/151527364/93f1900c-c59b-43e1-bb37-2ec187970bb2)

**Comment by Hockey86** [comment]
Hi, sorry the code is quite messy. The npz file at line 123 was generated from the code commented out above line 123, just because the commented code was really slow, therefore I ran it once and save the results to avoid repeated running the slow part.
